### ISSUE TITLE
Does v2.36.0 required Amplitude Analytics SDK Connector?

### ISSUE THREAD

**Issue by wada811** [amplitude/Amplitude-Android#320]
## Summary

After I upgraded Amplitude Android SDK to v2.36.0, I didn't add the following dependencies.

```
implementation 'com.amplitude:analytics-connector:1.0.0'
```

I see the following error.

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amplitude/analytics/connector/AnalyticsConnector;
    at com.amplitude.api.AmplitudeClient.<init>(AmplitudeClient.java:234)
    at com.amplitude.api.Amplitude.getInstance(Amplitude.java:44)
    at com.amplitude.api.Amplitude.getInstance(Amplitude.java:30)
```

Is Amplitude Analytics SDK Connector required?

If Amplitude Analytics SDK Connector is required, the following code might have a bad influence.

https://github.com/amplitude/Amplitude-Android/blob/b85357bd0cc1149792e893237bcb441988af2cf7/build.gradle#L135-L137

**Comment by bgiori** [comment]
@wada811 This issue has been fixed in `v2.36.1`.

Thanks again for reporting this issue and identifying the root cause.
